version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
exclude_patterns:
- "spec/"
- "test/"
